### ISSUE TITLE
Setup does not install shared object 

### ISSUE THREAD

**Issue by MarSianer1** [test-fullautomation/python-microservice-cleware-switch#11]
Running the installation routine on Linux does install all python files from top level but not the embedded folder structure libs/linux/*.so
So the library is finally not present and module fails to load the same.
Same can be observed in microservice-base with MicroserviceManagerGUI files. Also there all embedded file structures are not correctly copied

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
please look into this for 0.13.0
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Ready, but not yet integrated in 0.13.0

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Hello @test-fullautomation ,

Fixed by https://github.com/test-fullautomation/python-microservice-cleware-switch/pull/19

Thanks,
Cuong
