### ISSUE TITLE
Exception on disconnect from service

### ISSUE THREAD

**Issue by MarSianer1** [test-fullautomation/python-microservice-cleware-switch#12]
Attached test case will lead to exception when disconnect is called

[test.robot.txt](https://github.com/test-fullautomation/python-microservice-cleware-switch/files/15078475/test.robot.txt)

[exception.log](https://github.com/test-fullautomation/python-microservice-cleware-switch/files/15078503/exception.log)

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
please look into this for 0.13.0
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Ready, but not yet integrated in 0.13.0

**Comment by test-fullautomation** [comment]
Hi @milanac030988 ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Hello @test-fullautomation ,

There is no perfect solution yet. I have pushed an acceptable solution at https://github.com/test-fullautomation/robotframework-qconnect-base/pull/45 

Thanks,
Cuong
